---
title: "Quiz 1"
output: 
    html_document:
        keep_md: true
---

Muralidhar Areti  
Aug 9, 2015  

Q1  
```{r}
x = c(0.18, -1.54, 0.42, 0.95)
w = c(2, 1, 3, 1)

weighted.mean(x, w)
```

Q2  
```{r}
x <- c(0.8, 0.47, 0.51, 0.73, 0.36, 0.58, 0.57, 0.85, 0.44, 0.42)
y <- c(1.39, 0.72, 1.55, 0.48, 1.19, -1.59, 1.23, -0.65, 1.49, 0.05)

fit = lm(y ~ x - 1)
summary(fit)
```

Q3
```{r}
data(mtcars)
fit = lm(mpg ~ wt, mtcars)
summary(fit)
```

Q4
```{r}
corr_XY = 0.5
sd_XY = 2

beta = corr_XY * sd_XY
```

Q5
```{r}
corr_XY = 0.4
q1 = 1.5
q2 = q1 * corr_XY * 1 + 0

q2
```

Q6
```{r}
x <- c(8.58, 10.46, 9.01, 9.64, 8.86)

mu = mean(x)
sd = sd(x)

first_value = (x[1] - mu)/sd
first_value
```

Q7  
```{r}
x <- c(0.8, 0.47, 0.51, 0.73, 0.36, 0.58, 0.57, 0.85, 0.44, 0.42)
y <- c(1.39, 0.72, 1.55, 0.48, 1.19, -1.59, 1.23, -0.65, 1.49, 0.05)

fit = lm(y ~ x)
summary(fit)
```

Q8
```{r}
# it must be identically 0
```

Q9
```{r}
x <- c(0.8, 0.47, 0.51, 0.73, 0.36, 0.58, 0.57, 0.85, 0.44, 0.42)

mean(x)
```

Q10
```{r}
# var(y)/var(x)
```